# Generated by Django 5.0.3 on 2024-04-05 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="班级名")),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=50, verbose_name="密码")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teacher_images",
                        verbose_name="头像",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "teacher"), (1, "student")],
                        default=0,
                        verbose_name="角色",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_no",
                    models.CharField(max_length=20, unique=True, verbose_name="学号"),
                ),
                ("username", models.CharField(max_length=50, verbose_name="姓名")),
                ("password", models.CharField(max_length=50, verbose_name="密码")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="student_images",
                        verbose_name="头像",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "teacher"), (1, "student")],
                        default=1,
                        verbose_name="角色",
                    ),
                ),
                (
                    "classs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="app01.class",
                        verbose_name="所在班级",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.teacher",
                verbose_name="负责的老师",
            ),
        ),
    ]
