# Generated by Django 5.0.3 on 2024-04-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(
                default=15607249537, max_length=50, verbose_name="手机号"
            ),
            preserve_default=False,
        ),
    ]
