# Generated by Django 5.0.3 on 2024-04-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_student_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="phone",
            field=models.CharField(
                default=18978998767, max_length=50, verbose_name="手机号"
            ),
            preserve_default=False,
        ),
    ]
