# Generated by Django 5.0.3 on 2024-04-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_teacher_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.IntegerField(
                choices=[(0, "就业"), (1, "升学")], default=0, verbose_name="状态"
            ),
        ),
    ]
