# Generated by Django 5.0.3 on 2024-04-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0006_student_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="student_images/default.jpg",
                null=True,
                upload_to="student_images",
                verbose_name="头像",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="role",
            field=models.IntegerField(
                choices=[(0, "老师"), (1, "学生")], default=1, verbose_name="角色"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="role",
            field=models.IntegerField(
                choices=[(0, "老师"), (1, "学生")], default=0, verbose_name="角色"
            ),
        ),
    ]
