# Generated by Django 5.0.3 on 2024-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0007_alter_student_avatar_alter_student_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.AlterField(
            model_name="student",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="app1/default_avatar.jpg",
                null=True,
                upload_to="app01/",
                verbose_name="头像",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.IntegerField(
                choices=[(0, "就业"), (1, "升学")], default=0, verbose_name="毕业去向"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=50, verbose_name="用户名"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="password",
            field=models.CharField(max_length=100, verbose_name="密码"),
        ),
    ]
