# Generated by Django 5.0.3 on 2024-04-09 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0008_remove_student_teacher_alter_student_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="province",
            field=models.CharField(
                choices=[
                    (0, "北京"),
                    (1, "天津"),
                    (2, "河北"),
                    (3, "山西"),
                    (4, "内蒙古"),
                    (5, "辽宁"),
                    (6, "吉林"),
                    (7, "黑龙江"),
                    (8, "上海"),
                    (9, "江苏"),
                    (10, "浙江"),
                    (11, "安徽"),
                    (12, "福建"),
                    (13, "江西"),
                    (14, "山东"),
                    (15, "河南"),
                    (16, "湖北"),
                    (17, "湖南"),
                    (18, "广东"),
                    (19, "广西"),
                    (20, "海南"),
                    (21, "重庆"),
                    (22, "四川"),
                    (23, "贵州"),
                    (24, "云南"),
                    (25, "西藏"),
                    (26, "陕西"),
                    (27, "甘肃"),
                    (28, "青海"),
                    (29, "宁夏"),
                    (30, "新疆"),
                    (31, "台湾"),
                    (32, "香港"),
                    (33, "澳门"),
                ],
                default=16,
                max_length=20,
                verbose_name="省份",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="classs",
            field=models.ForeignKey(
                default=16,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="app01.class",
                verbose_name="所在班级",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="student_no",
            field=models.CharField(max_length=50, unique=True, verbose_name="学号"),
        ),
    ]
