# Generated by Django 5.0.3 on 2024-04-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0011_alter_class_name_alter_student_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(max_length=50, verbose_name="班级名"),
        ),
    ]
