# Generated by Django 5.0.3 on 2024-04-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0012_alter_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="是否查看到通知"),
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name=("创建时间",)),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="app01.teacher",
                    ),
                ),
            ],
        ),
    ]
