# Generated by Django 5.0.3 on 2024-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0013_student_is_read_notice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=("创建时间",)),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_read",
            field=models.IntegerField(
                choices=[(0, "未读"), (1, "已读")], default=0, verbose_name="已未读"
            ),
        ),
    ]
