# Generated by Django 5.0.3 on 2024-04-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0014_alter_notice_created_at_alter_student_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name=("创建时间",)),
        ),
    ]
