# Generated by Django 4.2.11 on 2024-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0015_alter_notice_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name": "班级", "verbose_name_plural": "班级"},
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={"verbose_name": "通知", "verbose_name_plural": "通知"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "学生", "verbose_name_plural": "学生"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "老师", "verbose_name_plural": "老师"},
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="班级名"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="student",
            name="province",
            field=models.IntegerField(
                choices=[
                    (0, "北京市"),
                    (1, "天津市"),
                    (2, "河北省"),
                    (3, "山西省"),
                    (4, "内蒙古自治区"),
                    (5, "辽宁省"),
                    (6, "吉林省"),
                    (7, "黑龙江省"),
                    (8, "上海市"),
                    (9, "江苏省"),
                    (10, "浙江省"),
                    (11, "安徽省"),
                    (12, "福建省"),
                    (13, "江西省"),
                    (14, "山东省"),
                    (15, "河南省"),
                    (16, "湖北省"),
                    (17, "湖南省"),
                    (18, "广东省"),
                    (19, "广西壮族自治区"),
                    (20, "海南省"),
                    (21, "重庆市"),
                    (22, "四川省"),
                    (23, "贵州省"),
                    (24, "云南省"),
                    (25, "西藏自治区"),
                    (26, "陕西省"),
                    (27, "甘肃省"),
                    (28, "青海省"),
                    (29, "宁夏回族自治区"),
                    (30, "新疆维吾尔自治区"),
                    (31, "台湾省"),
                    (32, "香港特别行政区"),
                    (33, "澳门特别行政区"),
                ],
                default=16,
                verbose_name="意向地区",
            ),
        ),
    ]
