# Generated by Django 4.2.9 on 2024-07-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0016_alter_class_options_alter_notice_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=255, verbose_name="岗位名字"
                    ),
                ),
                (
                    "address",
                    models.CharField(default="", max_length=255, verbose_name="省份"),
                ),
                (
                    "type",
                    models.CharField(default="", max_length=255, verbose_name="职业"),
                ),
                (
                    "educational",
                    models.CharField(default="", max_length=255, verbose_name="学历"),
                ),
                (
                    "workExperience",
                    models.CharField(
                        default="", max_length=255, verbose_name="工作经历"
                    ),
                ),
                (
                    "workTag",
                    models.CharField(
                        default="", max_length=2555, verbose_name="工作标签"
                    ),
                ),
                (
                    "salary",
                    models.CharField(default="", max_length=255, verbose_name="薪资"),
                ),
                (
                    "salaryMonth",
                    models.CharField(default="", max_length=255, verbose_name="年终奖"),
                ),
                (
                    "companyTags",
                    models.CharField(
                        default="", max_length=2555, verbose_name="公司福利"
                    ),
                ),
                (
                    "hrWork",
                    models.CharField(
                        default="", max_length=255, verbose_name="人事职位"
                    ),
                ),
                (
                    "hrName",
                    models.CharField(
                        default="", max_length=255, verbose_name="人事名字"
                    ),
                ),
                (
                    "pratice",
                    models.BooleanField(
                        default="", max_length=255, verbose_name="是否为实习单位"
                    ),
                ),
                (
                    "companyTitle",
                    models.CharField(
                        default="", max_length=255, verbose_name="公司名称"
                    ),
                ),
                (
                    "companyAvatar",
                    models.CharField(
                        default="", max_length=255, verbose_name="公司头像"
                    ),
                ),
                (
                    "companyNature",
                    models.CharField(
                        default="", max_length=255, verbose_name="公司性质"
                    ),
                ),
                (
                    "companyStatus",
                    models.CharField(
                        default="", max_length=255, verbose_name="公司状态"
                    ),
                ),
                (
                    "companyPeople",
                    models.CharField(
                        default="", max_length=255, verbose_name="公司人数"
                    ),
                ),
                (
                    "detailUrl",
                    models.CharField(
                        default="", max_length=2555, verbose_name="详情地址"
                    ),
                ),
                (
                    "companyUrl",
                    models.CharField(
                        default="", max_length=2555, verbose_name="公司详情地址"
                    ),
                ),
                (
                    "createTime",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "dist",
                    models.CharField(default="", max_length=255, verbose_name="行政区"),
                ),
            ],
            options={
                "verbose_name": "招聘信息",
                "verbose_name_plural": "招聘信息",
            },
        ),
    ]
