# Generated by Django 4.2.9 on 2024-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0017_jobinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, null=True, verbose_name="院校名称"),
                ),
                (
                    "location",
                    models.CharField(max_length=32, null=True, verbose_name="所在地"),
                ),
                (
                    "department",
                    models.CharField(max_length=32, null=True, verbose_name="院校隶属"),
                ),
                (
                    "is_research",
                    models.BooleanField(
                        choices=[(1, "研究生院"), (0, " ")],
                        max_length=32,
                        null=True,
                        verbose_name="是否有研究生院",
                    ),
                ),
                (
                    "is_auto_line",
                    models.BooleanField(
                        choices=[(1, "自划线"), (0, " ")],
                        max_length=32,
                        null=True,
                        verbose_name="是否为自划线院校",
                    ),
                ),
                (
                    "is_double_one",
                    models.BooleanField(
                        choices=[(1, "双一流"), (0, " ")],
                        max_length=32,
                        null=True,
                        verbose_name="是否为双一流院校",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="", max_length=255, verbose_name="图标链接"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        default="", max_length=255, verbose_name="院校链接"
                    ),
                ),
            ],
            options={
                "verbose_name": "院校",
                "verbose_name_plural": "院校",
            },
        ),
    ]
