# Generated by Django 4.2.9 on 2024-08-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0018_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
