# Generated by Django 4.2.9 on 2024-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0019_student_email_teacher_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
