# Generated by Django 4.2.9 on 2024-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0020_teacher_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
