# Generated by Django 4.2.9 on 2024-08-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0021_student_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="classes",
            field=models.ManyToManyField(
                related_name="notices", to="app01.class", verbose_name="班级"
            ),
        ),
    ]
